export const genderList = [
  { id: 0, name: "Man" },
  { id: 1, name: "Woman" },
];
export const shapeList = [
  { id: 0, name: "Round" },
  { id: 1, name: "Rectangular" },
  { id: 2, name: "Square" },
  { id: 3, name: "Cushion" },
  { id: 4, name: "Oval" },
  { id: 5, name: "Tonneau" },
];
export const typeList = [
  { id: 0, name: "Analog" },
  { id: 1, name: "Digital" },
  { id: 2, name: "Automatic" },
  { id: 3, name: "Chronograph" },
  { id: 4, name: "Diving" },
  { id: 5, name: "Dress" },
  { id: 6, name: "Quartz" },
  { id: 7, name: "Mechanical" },
  { id: 8, name: "Pilot" },
  { id: 9, name: "Field" },
  { id: 10, name: "Smart" },
  { id: 11, name: "Luxury" },
];
export const warrantyList = [
  { id: 0, name: "1 Year of Warranty" },
  { id: 1, name: "2 Years of Warranty" },
  { id: 2, name: "3 Years of Warranty" },
  { id: 3, name: "4 Years of Warranty" },
  { id: 4, name: "Lifetime Warranty" },
];
export const countryOfOriginList = [
  { id: 0, name: "Swiss" },
  { id: 1, name: "France" },
  { id: 2, name: "USA" },
  { id: 3, name: "UK" },
  { id: 4, name: "Italy" },
  { id: 5, name: "Germany" },
];
export const manufacturerList = [
  { id: 0, name: "Adriatica" },
  { id: 1, name: "Orient" },
  { id: 2, name: "Tissot" },
  { id: 3, name: "Anne Klein" },
  { id: 4, name: "Jaeger-LeCoultre" },
  { id: 5, name: "Audemars Piguet" },
  { id: 6, name: "Frédérique Constant" },
  { id: 7, name: "Piaget" },
  { id: 8, name: "Cartier" },
  { id: 9, name: "Harry Winston" },
  { id: 10, name: "Blancpain" },
  { id: 11, name: "Longines" },
  { id: 12, name: "Zenith" },
  { id: 13, name: "Tudor" },
  { id: 14, name: "Omega" },
  { id: 15, name: "Rolex" },
  { id: 16, name: "Patek Philippe" },
  { id: 17, name: "Vacheron Constantin" },
  { id: 18, name: "Van Cleef & Arpels" },
  { id: 19, name: "Tag Heuer" },
  { id: 20, name: "Panerai" },
  { id: 21, name: "Hublot" },
  { id: 22, name: "Breitling" },
  { id: 23, name: "Chopard" },
  { id: 24, name: "MeisterSinger" },
  { id: 25, name: "Bulgari" },
  { id: 26, name: "Breguet" },
  { id: 27, name: "Verdure Watches" },
  { id: 28, name: "Montblanc" },
];
